# Generated by Django 3.2 on 2023-03-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Ingredient_Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('cake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes.cake')),
            ],
        ),
    ]
